name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Initialize Node.js project
      run: npm init -y
    - name: Install Jest
      run: npm install --save-dev jest
    - name: Install Puppeteer
      run: npm i puppeteer
    - run: npm install  # Replaces npm ci since package-lock.json does not exist
    - run: npm run build --if-present
    - run: npm test
